services:
  - type: web
    name: tensorflow-web-app
    runtime: python
    region: oregon  # or frankfurt, singapore, etc.
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Home:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
